services:
  broker:
    container_name: mqtt_broker
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - bridge_network

  mqtt_listener:
    depends_on:
      - broker
    container_name: mqtt_listener
    build: 
      context: .
      dockerfile: "Dockerfile"
      target: "Dev"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.1.0/24 